# Generated by Django 4.1.3 on 2024-01-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travelpackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('includes', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('special_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
